apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pietroaragona/gitops-cookbook-sc.git
    targetRevision: HEAD
    path: ch07/bgd
  destination:
    server: https://kubernetes.default.svc
    namespace: bgd
